
/**
* HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, December 23, 2012 7:18:35 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
